# Use Node.js
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY . .

# Install dependencies
RUN npm install

# Copy source code


# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]